---
- name : Copy the file to remote node and read the file 
  hosts: testservers
  gather_facts: false
  vars:
    file_name: "test1.txt"

  tasks:
    - name: copy file to nodes
      copy:
       src: "/home/ashok/ansible/{{file_name}}"
       dest: "/tmp/{{file_name}}"

    - name : read the content 
      shell :
        cmd: cat /tmp/{{ file_name }}
      register: content_text

    - name: print the content
      debug:
        var: content_text

    - name: delete the file
      file:
        dest: /tmp/{{ file_name }}
        state: absent
      register: filedelstatus
     
    - name: print
      debug:
        msg: 
          - " File : {{ file_name }} is delete from remote node "
      when: filedelstatus.changed == true

